# Nome do workflow que aparece no github
name: CI/CD Pipeline

# Executa a cada Push ou Pull request na main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Lista de Jobs
jobs: 
  # Job 1: CI
  ci:
    runs-on: ubuntu-latest

    # Lista de passos do job
    steps:
        # Passo 1: Baixar o código do repositório
      - name: Checkout do código
        uses: actions/checkout@v4

        # Passo 2: Configurar Java 21
      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

        # Passo 3: Executar testes
      - name: Executar testes
        run: mvn -B test --file pom.xml
